/**
 * Cloud SQL (PostgreSQL 15) — private IP only, IAM authentication enabled.
 *
 * One instance per env. Database named `stylist`. Application connects via
 *   unix socket: /cloudsql/<connection_name>     (Cloud Run Cloud SQL Auth Proxy)
 *   private IP : <private_ip>:5432               (GKE / VM)
 *
 * Passwordless: Cloud Run service accounts authenticate via IAM
 * (`cloudsql.iam_authentication=on`). One bootstrap superuser exists for
 * migrations; its password is generated by Terraform and stored in Secret Manager.
 */

resource "random_password" "root" {
  length  = 32
  special = false
}

resource "google_sql_database_instance" "primary" {
  name             = "stylist-${var.env}-pg"
  project          = var.project_id
  region           = var.region
  database_version = "POSTGRES_15"

  deletion_protection = var.env == "prod"

  settings {
    tier              = var.tier
    edition           = "ENTERPRISE"
    availability_type = var.high_availability ? "REGIONAL" : "ZONAL"
    disk_size         = var.disk_size_gb
    disk_type         = "PD_SSD"
    disk_autoresize   = true

    backup_configuration {
      enabled                        = true
      point_in_time_recovery_enabled = true
      start_time                     = "03:00"
      transaction_log_retention_days = 7
      backup_retention_settings {
        retained_backups = var.env == "prod" ? 30 : 7
      }
    }

    ip_configuration {
      ipv4_enabled                                  = false
      private_network                               = var.vpc_self_link
      enable_private_path_for_google_cloud_services = true
    }

    database_flags {
      name  = "cloudsql.iam_authentication"
      value = "on"
    }

    insights_config {
      query_insights_enabled  = true
      record_application_tags = true
      record_client_address   = false
    }

    user_labels = var.labels
  }

  lifecycle {
    ignore_changes = [settings[0].disk_size]
  }
}

resource "google_sql_database" "stylist" {
  name     = "stylist"
  project  = var.project_id
  instance = google_sql_database_instance.primary.name
}

# Bootstrap superuser used only by the migration job.
resource "google_sql_user" "root" {
  name     = "stylist-root"
  project  = var.project_id
  instance = google_sql_database_instance.primary.name
  password = random_password.root.result
}

resource "google_secret_manager_secret" "root_password" {
  project   = var.project_id
  secret_id = "stylist-${var.env}-pg-root-password"
  replication { auto {} }
  labels = var.labels
}

resource "google_secret_manager_secret_version" "root_password" {
  secret      = google_secret_manager_secret.root_password.id
  secret_data = random_password.root.result
}

# IAM-authenticated user — the runtime service account connects as itself.
resource "google_sql_user" "iam_runtime" {
  count    = var.iam_user_email == "" ? 0 : 1
  name     = trimsuffix(var.iam_user_email, ".gserviceaccount.com")
  project  = var.project_id
  instance = google_sql_database_instance.primary.name
  type     = "CLOUD_IAM_SERVICE_ACCOUNT"
}
